name: backend
channels:
  - anaconda
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python==3.11.11
  - websockets
  - datasets
  - pandas
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - requests
  - pip:
    - qdrant_client 
    - fastembed
    - sentence-transformers >= 3.4.1
    - transformers >= 4.48
    - cohere
    - google-generativeai
    - get_code_from_markdown
